import React from "react";
import {
  DiReact,
  DiNodejs,
  DiPython,
  DiJava,
  DiAws,
  DiDocker,
  DiJavascript,
  DiHtml5,
  DiCss3,
  DiMongodb,
  DiPostgresql,
  DiGit,
  DiLinux,
  DiRust,
  DiGo,
  DiRuby,
  DiPhp,
  DiMysql,
  DiRedis,
  DiSass,
  DiBootstrap,
} from "react-icons/di";
import {
  SiTypescript,
  SiNextdotjs,
  SiTailwindcss,
  SiVuedotjs,
  SiSvelte,
  SiExpress,
  SiFastapi,
  SiSpring,
  SiDotnet,
  SiGraphql,
  SiKubernetes,
  SiGooglecloud,
  SiFigma,
  SiPostman,
  SiCplusplus,
  SiSharp,
  SiFlutter,
  SiDart,
  SiSwift,
  SiKotlin,
  SiFirebase,
  SiSupabase,
  SiPrisma,
  SiDjango,
  SiFlask,
  SiRedux,
} from "react-icons/si";
import { Code } from "lucide-react";

export type DeviconSkill = {
  name: string;
  icon: React.ComponentType<{ className?: string }>;
};

export const DEVICON_SKILLS: DeviconSkill[] = [
  { name: "React", icon: DiReact },
  { name: "TypeScript", icon: SiTypescript },
  { name: "Node.js", icon: DiNodejs },
  { name: "Python", icon: DiPython },
  { name: "JavaScript", icon: DiJavascript },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "AWS", icon: DiAws },
  { name: "Docker", icon: DiDocker },
  { name: "Java", icon: DiJava },
  { name: "Tailwind CSS", icon: SiTailwindcss },
  { name: "GraphQL", icon: SiGraphql },
  { name: "PostgreSQL", icon: DiPostgresql },
  { name: "MongoDB", icon: DiMongodb },
  { name: "MySQL", icon: DiMysql },
  { name: "Redis", icon: DiRedis },
  { name: "Kubernetes", icon: SiKubernetes },
  { name: "C++", icon: SiCplusplus },
  { name: "C#", icon: SiSharp },
  { name: ".NET", icon: SiDotnet },
  { name: "Go", icon: DiGo },
  { name: "Rust", icon: DiRust },
  { name: "Vue.js", icon: SiVuedotjs },
  { name: "Svelte", icon: SiSvelte },
  { name: "Express.js", icon: SiExpress },
  { name: "FastAPI", icon: SiFastapi },
  { name: "Django", icon: SiDjango },
  { name: "Flask", icon: SiFlask },
  { name: "Spring", icon: SiSpring },
  { name: "Ruby", icon: DiRuby },
  { name: "PHP", icon: DiPhp },
  { name: "HTML5", icon: DiHtml5 },
  { name: "CSS3", icon: DiCss3 },
  { name: "Sass", icon: DiSass },
  { name: "Bootstrap", icon: DiBootstrap },
  { name: "Git", icon: DiGit },
  { name: "Linux", icon: DiLinux },
  { name: "GCP", icon: SiGooglecloud },
  { name: "Figma", icon: SiFigma },
  { name: "Postman", icon: SiPostman },
  { name: "Flutter", icon: SiFlutter },
  { name: "Dart", icon: SiDart },
  { name: "Swift", icon: SiSwift },
  { name: "Kotlin", icon: SiKotlin },
  { name: "Firebase", icon: SiFirebase },
  { name: "Supabase", icon: SiSupabase },
  { name: "Prisma", icon: SiPrisma },
  { name: "Redux", icon: SiRedux },
];

export function getSkillIcon(skillName: string): React.ComponentType<{ className?: string }> {
  const match = DEVICON_SKILLS.find(
    (s) => s.name.toLowerCase() === skillName.trim().toLowerCase()
  );
  return match ? match.icon : Code;
}
